GET http://localhost:3000/

###
POST http://localhost:3000/

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "email": "t2@t.com",
    "password": "aA1$aA1$"
}

###
GET http://localhost:3000/users/fnjekdnfjekr

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "sku": "FDZFZEF"
}

###
POST http://localhost:3000/books
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "ISBN": "FDZFZEF"
}

###
GET http://localhost:3000/authors

###
POST http://localhost:3000/authors
Content-Type: application/json

{
    "lastname": "Dawson"
}

###
GET http://localhost:3000/users/018aff6d-2c04-72e8-9f08-5f4ddade10f0
Cookies: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOGI3ZmFlLWUxNDItNzZiYi05NTlkLTJhMjY5YzFhNjNjYyIsImZpcnN0bmFtZSI6bnVsbCwibGFzdG5hbWUiOm51bGwsImlhdCI6MTY5ODY1NDI5MywiZXhwIjoxNzMwMjExODkzfQ.LgTwFIg7VJuS3Ia4ODgzhl7yEnDeEmM3WgHqI5JqEIc; Path=/; HttpOnly

###
PATCH http://localhost:3000/users/018aff66-1cf9-72f4-be5e-28227e0d19c5
Content-Type: application/json

{
    "password": "Azerty1234!"
}

###
PATCH http://localhost:3000/users/018b7fae-e142-76bb-959d-2a269c1a63cc
Content-Type: application/json

{
    "password": "zrzef"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "t2@t.com",
    "password": "zrzef"
}

###
GET http://localhost:3000/articles


###
POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "My Article",
    "UserId": "018aff66-1cf9-72f4-be5e-28227e0d19c5"
}